export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      veterinarians: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          clinic_name: string | null;
          license_number: string;
          license_state: string | null;
          license_expiry_date: string | null;
          phone: string | null;
          address: string | null;
          status: 'pending' | 'approved' | 'suspended' | 'rejected';
          approved_at: string | null;
          approved_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          email: string;
          full_name: string;
          clinic_name?: string | null;
          license_number: string;
          license_state?: string | null;
          license_expiry_date?: string | null;
          phone?: string | null;
          address?: string | null;
          status?: 'pending' | 'approved' | 'suspended' | 'rejected';
          approved_at?: string | null;
          approved_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          clinic_name?: string | null;
          license_number?: string;
          license_state?: string | null;
          license_expiry_date?: string | null;
          phone?: string | null;
          address?: string | null;
          status?: 'pending' | 'approved' | 'suspended' | 'rejected';
          approved_at?: string | null;
          approved_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      administrators: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          role: 'admin' | 'super_admin' | 'monitor';
          created_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          email: string;
          full_name: string;
          role?: 'admin' | 'super_admin' | 'monitor';
          created_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          role?: 'admin' | 'super_admin' | 'monitor';
          created_at?: string;
          deleted_at?: string | null;
        };
      };
      sites: {
        Row: {
          id: string;
          name: string;
          address: string;
          city: string | null;
          state: string | null;
          zip: string | null;
          country: string;
          veterinarian_id: string | null;
          readiness: 'not_started' | 'in_progress' | 'ready' | 'inspection_required' | 'approved';
          inspection_date: string | null;
          approval_date: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          address: string;
          city?: string | null;
          state?: string | null;
          zip?: string | null;
          country?: string;
          veterinarian_id?: string | null;
          readiness?: 'not_started' | 'in_progress' | 'ready' | 'inspection_required' | 'approved';
          inspection_date?: string | null;
          approval_date?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          address?: string;
          city?: string | null;
          state?: string | null;
          zip?: string | null;
          country?: string;
          veterinarian_id?: string | null;
          readiness?: 'not_started' | 'in_progress' | 'ready' | 'inspection_required' | 'approved';
          inspection_date?: string | null;
          approval_date?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      patients: {
        Row: {
          id: string;
          patient_number: string;
          horse_name: string;
          breed: string | null;
          age_years: number | null;
          age_months: number | null;
          sex: 'gelding' | 'stallion' | 'mare' | null;
          weight_kg: number | null;
          owner_name: string;
          owner_phone: string | null;
          owner_email: string | null;
          veterinarian_id: string;
          site_id: string | null;
          status: 'screening' | 'enrolled' | 'active' | 'completed' | 'withdrawn' | 'locked' | 'frozen';
          enrollment_date: string | null;
          completion_date: string | null;
          withdrawal_date: string | null;
          withdrawal_reason: string | null;
          locked_at: string | null;
          locked_by: string | null;
          frozen_at: string | null;
          frozen_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          patient_number?: string;
          horse_name: string;
          breed?: string | null;
          age_years?: number | null;
          age_months?: number | null;
          sex?: 'gelding' | 'stallion' | 'mare' | null;
          weight_kg?: number | null;
          owner_name: string;
          owner_phone?: string | null;
          owner_email?: string | null;
          veterinarian_id: string;
          site_id?: string | null;
          status?: 'screening' | 'enrolled' | 'active' | 'completed' | 'withdrawn' | 'locked' | 'frozen';
          enrollment_date?: string | null;
          completion_date?: string | null;
          withdrawal_date?: string | null;
          withdrawal_reason?: string | null;
          locked_at?: string | null;
          locked_by?: string | null;
          frozen_at?: string | null;
          frozen_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          patient_number?: string;
          horse_name?: string;
          breed?: string | null;
          age_years?: number | null;
          age_months?: number | null;
          sex?: 'gelding' | 'stallion' | 'mare' | null;
          weight_kg?: number | null;
          owner_name?: string;
          owner_phone?: string | null;
          owner_email?: string | null;
          veterinarian_id?: string;
          site_id?: string | null;
          status?: 'screening' | 'enrolled' | 'active' | 'completed' | 'withdrawn' | 'locked' | 'frozen';
          enrollment_date?: string | null;
          completion_date?: string | null;
          withdrawal_date?: string | null;
          withdrawal_reason?: string | null;
          locked_at?: string | null;
          locked_by?: string | null;
          frozen_at?: string | null;
          frozen_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      study_settings: {
        Row: {
          id: string;
          inad_number: string;
          protocol_version: string;
          protocol_start_hour: number;
          sponsor_name: string;
          principal_investigator: string | null;
          study_title: string | null;
          notes: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          inad_number?: string;
          protocol_version?: string;
          protocol_start_hour?: number;
          sponsor_name?: string;
          principal_investigator?: string | null;
          study_title?: string | null;
          notes?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          inad_number?: string;
          protocol_version?: string;
          protocol_start_hour?: number;
          sponsor_name?: string;
          principal_investigator?: string | null;
          study_title?: string | null;
          notes?: string | null;
          updated_at?: string;
        };
      };
      eligibility_screenings: {
        Row: {
          id: string;
          patient_id: string;
          veterinarian_id: string;
          inclusion_criteria: Json;
          exclusion_criteria: Json;
          laminitis_history: string | null;
          previous_treatments: string | null;
          current_medications: string | null;
          inclusion_criteria_met: boolean | null;
          exclusion_criteria_met: boolean | null;
          is_eligible: boolean;
          screened_at: string;
          notes: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          patient_id: string;
          veterinarian_id: string;
          inclusion_criteria?: Json;
          exclusion_criteria?: Json;
          laminitis_history?: string | null;
          previous_treatments?: string | null;
          current_medications?: string | null;
          inclusion_criteria_met?: boolean | null;
          exclusion_criteria_met?: boolean | null;
          is_eligible?: boolean;
          screened_at?: string;
          notes?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          patient_id?: string;
          veterinarian_id?: string;
          inclusion_criteria?: Json;
          exclusion_criteria?: Json;
          laminitis_history?: string | null;
          previous_treatments?: string | null;
          current_medications?: string | null;
          inclusion_criteria_met?: boolean | null;
          exclusion_criteria_met?: boolean | null;
          is_eligible?: boolean;
          screened_at?: string;
          notes?: string | null;
          deleted_at?: string | null;
        };
      };
      protocol_versions: {
        Row: {
          id: string;
          version: string;
          effective_date: string;
          summary: string;
          document_url: string | null;
          is_current: boolean;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          version: string;
          effective_date: string;
          summary: string;
          document_url?: string | null;
          is_current?: boolean;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          version?: string;
          effective_date?: string;
          summary?: string;
          document_url?: string | null;
          is_current?: boolean;
          created_by?: string | null;
          created_at?: string;
        };
      };
      informed_consents: {
        Row: {
          id: string;
          patient_id: string;
          owner_name: string;
          owner_signature_url: string | null;
          consent_status: 'pending' | 'signed' | 'withdrawn' | 'expired';
          signed_at: string | null;
          withdrawn_at: string | null;
          version: string;
          document_url: string | null;
          created_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          patient_id: string;
          owner_name: string;
          owner_signature_url?: string | null;
          consent_status?: 'pending' | 'signed' | 'withdrawn' | 'expired';
          signed_at?: string | null;
          withdrawn_at?: string | null;
          version?: string;
          document_url?: string | null;
          created_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          patient_id?: string;
          owner_name?: string;
          owner_signature_url?: string | null;
          consent_status?: 'pending' | 'signed' | 'withdrawn' | 'expired';
          signed_at?: string | null;
          withdrawn_at?: string | null;
          version?: string;
          document_url?: string | null;
          created_at?: string;
          deleted_at?: string | null;
        };
      };
      treatments: {
        Row: {
          id: string;
          patient_id: string;
          veterinarian_id: string;
          treatment_number: number;
          treatment_date: string;
          drug_lot_number: string | null;
          dose_mg: number | null;
          route: string;
          administered_by: string | null;
          administered_at: string | null;
          next_treatment_date: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          patient_id: string;
          veterinarian_id: string;
          treatment_number: number;
          treatment_date: string;
          drug_lot_number?: string | null;
          dose_mg?: number | null;
          route?: string;
          administered_by?: string | null;
          administered_at?: string | null;
          next_treatment_date?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          patient_id?: string;
          veterinarian_id?: string;
          treatment_number?: number;
          treatment_date?: string;
          drug_lot_number?: string | null;
          dose_mg?: number | null;
          route?: string;
          administered_by?: string | null;
          administered_at?: string | null;
          next_treatment_date?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      clinical_assessments: {
        Row: {
          id: string;
          patient_id: string;
          veterinarian_id: string;
          assessment_date: string;
          obel_score: '0' | '1' | '2' | '3' | '4' | '5' | null;
          lameness_grade: number | null;
          hoof_temperature: string | null;
          digital_pulse: string | null;
          hoof_tester_response: string | null;
          gait_analysis: string | null;
          body_condition_score: number | null;
          heart_rate: number | null;
          respiratory_rate: number | null;
          temperature_celsius: number | null;
          general_appearance: string | null;
          overall_impression: string | null;
          created_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          patient_id: string;
          veterinarian_id: string;
          assessment_date: string;
          obel_score?: '0' | '1' | '2' | '3' | '4' | '5' | null;
          lameness_grade?: number | null;
          hoof_temperature?: string | null;
          digital_pulse?: string | null;
          hoof_tester_response?: string | null;
          gait_analysis?: string | null;
          body_condition_score?: number | null;
          heart_rate?: number | null;
          respiratory_rate?: number | null;
          temperature_celsius?: number | null;
          general_appearance?: string | null;
          overall_impression?: string | null;
          created_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          patient_id?: string;
          veterinarian_id?: string;
          assessment_date?: string;
          obel_score?: '0' | '1' | '2' | '3' | '4' | '5' | null;
          lameness_grade?: number | null;
          hoof_temperature?: string | null;
          digital_pulse?: string | null;
          hoof_tester_response?: string | null;
          gait_analysis?: string | null;
          body_condition_score?: number | null;
          heart_rate?: number | null;
          respiratory_rate?: number | null;
          temperature_celsius?: number | null;
          general_appearance?: string | null;
          overall_impression?: string | null;
          created_at?: string;
          deleted_at?: string | null;
        };
      };
      treatment_outcomes: {
        Row: {
          id: string;
          patient_id: string;
          veterinarian_id: string;
          outcome_scale: string;
          score: number | null;
          outcome_date: string;
          notes: string | null;
          signed_at: string | null;
          created_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          patient_id: string;
          veterinarian_id: string;
          outcome_scale: string;
          score?: number | null;
          outcome_date: string;
          notes?: string | null;
          signed_at?: string | null;
          created_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          patient_id?: string;
          veterinarian_id?: string;
          outcome_scale?: string;
          score?: number | null;
          outcome_date?: string;
          notes?: string | null;
          signed_at?: string | null;
          created_at?: string;
          deleted_at?: string | null;
        };
      };
      lab_results: {
        Row: {
          id: string;
          patient_id: string;
          veterinarian_id: string;
          lab_name: string | null;
          sample_date: string;
          sample_type: string | null;
          test_name: string;
          result_value: string | null;
          reference_range: string | null;
          unit: string | null;
          is_abnormal: boolean;
          is_critical: boolean;
          report_url: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          patient_id: string;
          veterinarian_id: string;
          lab_name?: string | null;
          sample_date: string;
          sample_type?: string | null;
          test_name: string;
          result_value?: string | null;
          reference_range?: string | null;
          unit?: string | null;
          is_abnormal?: boolean;
          is_critical?: boolean;
          report_url?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          patient_id?: string;
          veterinarian_id?: string;
          lab_name?: string | null;
          sample_date?: string;
          sample_type?: string | null;
          test_name?: string;
          result_value?: string | null;
          reference_range?: string | null;
          unit?: string | null;
          is_abnormal?: boolean;
          is_critical?: boolean;
          report_url?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
          deleted_at?: string | null;
        };
      };
      videos: {
        Row: {
          id: string;
          patient_id: string;
          uploaded_by: string;
          file_name: string;
          storage_path: string;
          file_size_bytes: number | null;
          mime_type: string | null;
          video_type: 'gait_analysis' | 'treatment' | 'adverse_event' | 'general';
          description: string | null;
          recorded_at: string | null;
          uploaded_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          patient_id: string;
          uploaded_by: string;
          file_name: string;
          storage_path: string;
          file_size_bytes?: number | null;
          mime_type?: string | null;
          video_type?: 'gait_analysis' | 'treatment' | 'adverse_event' | 'general';
          description?: string | null;
          recorded_at?: string | null;
          uploaded_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          patient_id?: string;
          uploaded_by?: string;
          file_name?: string;
          storage_path?: string;
          file_size_bytes?: number | null;
          mime_type?: string | null;
          video_type?: 'gait_analysis' | 'treatment' | 'adverse_event' | 'general';
          description?: string | null;
          recorded_at?: string | null;
          uploaded_at?: string;
          deleted_at?: string | null;
        };
      };
      clinical_notes: {
        Row: {
          id: string;
          patient_id: string;
          veterinarian_id: string;
          note_type: 'general' | 'treatment' | 'assessment' | 'adverse_event' | 'protocol_deviation';
          content: string;
          is_important: boolean;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          patient_id: string;
          veterinarian_id: string;
          note_type?: 'general' | 'treatment' | 'assessment' | 'adverse_event' | 'protocol_deviation';
          content: string;
          is_important?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          patient_id?: string;
          veterinarian_id?: string;
          note_type?: 'general' | 'treatment' | 'assessment' | 'adverse_event' | 'protocol_deviation';
          content?: string;
          is_important?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      adverse_events: {
        Row: {
          id: string;
          patient_id: string;
          veterinarian_id: string;
          ae_number: string;
          onset_date: string;
          resolution_date: string | null;
          description: string;
          severity: 'mild' | 'moderate' | 'severe' | 'life_threatening';
          causality: 'unrelated' | 'unlikely' | 'possible' | 'probable' | 'definite' | null;
          outcome: 'ongoing' | 'resolved' | 'resolved_with_sequelae' | 'fatal' | 'unknown';
          action_taken: string | null;
          is_serious: boolean;
          is_reported_to_fda: boolean;
          fda_report_date: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          patient_id: string;
          veterinarian_id: string;
          ae_number: string;
          onset_date: string;
          resolution_date?: string | null;
          description: string;
          severity: 'mild' | 'moderate' | 'severe' | 'life_threatening';
          causality?: 'unrelated' | 'unlikely' | 'possible' | 'probable' | 'definite' | null;
          outcome?: 'ongoing' | 'resolved' | 'resolved_with_sequelae' | 'fatal' | 'unknown';
          action_taken?: string | null;
          is_serious?: boolean;
          is_reported_to_fda?: boolean;
          fda_report_date?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          patient_id?: string;
          veterinarian_id?: string;
          ae_number?: string;
          onset_date?: string;
          resolution_date?: string | null;
          description?: string;
          severity?: 'mild' | 'moderate' | 'severe' | 'life_threatening';
          causality?: 'unrelated' | 'unlikely' | 'possible' | 'probable' | 'definite' | null;
          outcome?: 'ongoing' | 'resolved' | 'resolved_with_sequelae' | 'fatal' | 'unknown';
          action_taken?: string | null;
          is_serious?: boolean;
          is_reported_to_fda?: boolean;
          fda_report_date?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      protocol_deviations: {
        Row: {
          id: string;
          patient_id: string;
          veterinarian_id: string;
          deviation_type: 'inclusion_criteria' | 'dosing' | 'schedule' | 'procedure' | 'documentation' | 'other';
          severity: 'minor' | 'major' | 'critical';
          description: string;
          date_occurred: string;
          corrective_action: string | null;
          preventive_action: string | null;
          is_closed: boolean;
          closed_by: string | null;
          closed_at: string | null;
          created_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          patient_id: string;
          veterinarian_id: string;
          deviation_type: 'inclusion_criteria' | 'dosing' | 'schedule' | 'procedure' | 'documentation' | 'other';
          severity: 'minor' | 'major' | 'critical';
          description: string;
          date_occurred: string;
          corrective_action?: string | null;
          preventive_action?: string | null;
          is_closed?: boolean;
          closed_by?: string | null;
          closed_at?: string | null;
          created_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          patient_id?: string;
          veterinarian_id?: string;
          deviation_type?: 'inclusion_criteria' | 'dosing' | 'schedule' | 'procedure' | 'documentation' | 'other';
          severity?: 'minor' | 'major' | 'critical';
          description?: string;
          date_occurred?: string;
          corrective_action?: string | null;
          preventive_action?: string | null;
          is_closed?: boolean;
          closed_by?: string | null;
          closed_at?: string | null;
          created_at?: string;
          deleted_at?: string | null;
        };
      };
      monitoring_visits: {
        Row: {
          id: string;
          site_id: string;
          visit_type: 'pre_study' | 'periodic' | 'for_cause' | 'close_out';
          scheduled_date: string;
          completed_date: string | null;
          monitor_name: string | null;
          findings: string | null;
          capa_items: string | null;
          follow_up_required: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          site_id: string;
          visit_type: 'pre_study' | 'periodic' | 'for_cause' | 'close_out';
          scheduled_date: string;
          completed_date?: string | null;
          monitor_name?: string | null;
          findings?: string | null;
          capa_items?: string | null;
          follow_up_required?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          site_id?: string;
          visit_type?: 'pre_study' | 'periodic' | 'for_cause' | 'close_out';
          scheduled_date?: string;
          completed_date?: string | null;
          monitor_name?: string | null;
          findings?: string | null;
          capa_items?: string | null;
          follow_up_required?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      drug_shipments: {
        Row: {
          id: string;
          shipment_number: string;
          tracking_number: string | null;
          carrier: string | null;
          site_id: string | null;
          veterinarian_id: string | null;
          status: 'pending' | 'shipped' | 'in_transit' | 'delivered' | 'returned' | 'lost';
          shipped_at: string | null;
          estimated_arrival: string | null;
          delivered_at: string | null;
          received_by: string | null;
          condition_on_arrival: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          shipment_number?: string;
          tracking_number?: string | null;
          carrier?: string | null;
          site_id?: string | null;
          veterinarian_id?: string | null;
          status?: 'pending' | 'shipped' | 'in_transit' | 'delivered' | 'returned' | 'lost';
          shipped_at?: string | null;
          estimated_arrival?: string | null;
          delivered_at?: string | null;
          received_by?: string | null;
          condition_on_arrival?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          shipment_number?: string;
          tracking_number?: string | null;
          carrier?: string | null;
          site_id?: string | null;
          veterinarian_id?: string | null;
          status?: 'pending' | 'shipped' | 'in_transit' | 'delivered' | 'returned' | 'lost';
          shipped_at?: string | null;
          estimated_arrival?: string | null;
          delivered_at?: string | null;
          received_by?: string | null;
          condition_on_arrival?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      bottle_inventory: {
        Row: {
          id: string;
          shipment_id: string | null;
          bottle_number: string;
          lot_number: string;
          expiration_date: string;
          site_id: string | null;
          veterinarian_id: string | null;
          status: 'in_stock' | 'dispensed' | 'returned' | 'destroyed' | 'expired';
          dispensed_to_patient_id: string | null;
          dispensed_at: string | null;
          returned_at: string | null;
          destroyed_at: string | null;
          destroyed_reason: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          shipment_id?: string | null;
          bottle_number?: string;
          lot_number: string;
          expiration_date: string;
          site_id?: string | null;
          veterinarian_id?: string | null;
          status?: 'in_stock' | 'dispensed' | 'returned' | 'destroyed' | 'expired';
          rendered_to_patient_id?: string | null;
          dispensed_at?: string | null;
          returned_at?: string | null;
          destroyed_at?: string | null;
          destroyed_reason?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          shipment_id?: string | null;
          bottle_number?: string;
          lot_number?: string;
          expiration_date?: string;
          site_id?: string | null;
          veterinarian_id?: string | null;
          status?: 'in_stock' | 'dispensed' | 'returned' | 'destroyed' | 'expired';
          dispensed_to_patient_id?: string | null;
          dispensed_at?: string | null;
          returned_at?: string | null;
          destroyed_at?: string | null;
          destroyed_reason?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      storage_confirmations: {
        Row: {
          id: string;
          site_id: string;
          veterinarian_id: string;
          storage_type: 'refrigerator' | 'freezer' | 'room_temp' | 'secure_cabinet';
          temperature_celsius: number | null;
          humidity_percent: number | null;
          is_secure: boolean;
          is_temperature_monitored: boolean;
          status: 'pending' | 'confirmed' | 'violation';
          confirmed_at: string | null;
          photo_url: string | null;
          notes: string | null;
          created_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          site_id: string;
          veterinarian_id: string;
          storage_type?: 'refrigerator' | 'freezer' | 'room_temp' | 'secure_cabinet';
          temperature_celsius?: number | null;
          humidity_percent?: number | null;
          is_secure?: boolean;
          is_temperature_monitored?: boolean;
          status?: 'pending' | 'confirmed' | 'violation';
          confirmed_at?: string | null;
          photo_url?: string | null;
          notes?: string | null;
          created_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          site_id?: string;
          veterinarian_id?: string;
          storage_type?: 'refrigerator' | 'freezer' | 'room_temp' | 'secure_cabinet';
          temperature_celsius?: number | null;
          humidity_percent?: number | null;
          is_secure?: boolean;
          is_temperature_monitored?: boolean;
          status?: 'pending' | 'confirmed' | 'violation';
          confirmed_at?: string | null;
          photo_url?: string | null;
          notes?: string | null;
          created_at?: string;
          deleted_at?: string | null;
        };
      };
      fda_correspondence: {
        Row: {
          id: string;
          reference_number: string;
          correspondence_type: 'submission' | 'response' | 'inquiry' | 'inspection' | 'safety_report';
          subject: string;
          content: string | null;
          document_url: string | null;
          sponsor_name: string;
          sent_by: string | null;
          sent_at: string | null;
          received_at: string | null;
          is_archived: boolean;
          created_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          reference_number?: string;
          correspondence_type: 'submission' | 'response' | 'inquiry' | 'inspection' | 'safety_report';
          subject: string;
          content?: string | null;
          document_url?: string | null;
          sponsor_name?: string;
          sent_by?: string | null;
          sent_at?: string | null;
          received_at?: string | null;
          is_archived?: boolean;
          created_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          reference_number?: string;
          correspondence_type?: 'submission' | 'response' | 'inquiry' | 'inspection' | 'safety_report';
          subject?: string;
          content?: string | null;
          document_url?: string | null;
          sponsor_name?: string;
          sent_by?: string | null;
          sent_at?: string | null;
          received_at?: string | null;
          is_archived?: boolean;
          created_at?: string;
          deleted_at?: string | null;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          user_id: string | null;
          user_email: string | null;
          user_role: string | null;
          action: 'create' | 'read' | 'update' | 'delete' | 'login' | 'logout' | 'export' | 'lock' | 'freeze' | 'approve' | 'reject' | 'ship' | 'receive';
          table_name: string | null;
          record_id: string | null;
          old_values: Json | null;
          new_values: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          session_id: string | null;
          reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          user_email?: string | null;
          user_role?: string | null;
          action: 'create' | 'read' | 'update' | 'delete' | 'login' | 'logout' | 'export' | 'lock' | 'freeze' | 'approve' | 'reject' | 'ship' | 'receive';
          table_name?: string | null;
          record_id?: string | null;
          old_values?: Json | null;
          new_values?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          session_id?: string | null;
          reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          user_email?: string | null;
          user_role?: string | null;
          action?: 'create' | 'read' | 'update' | 'delete' | 'login' | 'logout' | 'export' | 'lock' | 'freeze' | 'approve' | 'reject' | 'ship' | 'receive';
          table_name?: string | null;
          record_id?: string | null;
          old_values?: Json | null;
          new_values?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          session_id?: string | null;
          reason?: string | null;
          created_at?: string;
        };
      };
    };
    Functions: {};
    Enums: {
      patient_status: 'screening' | 'enrolled' | 'active' | 'completed' | 'withdrawn' | 'locked' | 'frozen';
      consent_status: 'pending' | 'signed' | 'withdrawn' | 'expired';
      vet_status: 'pending' | 'approved' | 'suspended' | 'rejected';
      obel_score: '0' | '1' | '2' | '3' | '4' | '5';
      ae_severity: 'mild' | 'moderate' | 'severe' | 'life_threatening';
      ae_causality: 'unrelated' | 'unlikely' | 'possible' | 'probable' | 'definite';
      ae_outcome: 'ongoing' | 'resolved' | 'resolved_with_sequelae' | 'fatal' | 'unknown';
      shipment_status: 'pending' | 'shipped' | 'in_transit' | 'delivered' | 'returned' | 'lost';
      bottle_status: 'in_stock' | 'dispensed' | 'returned' | 'destroyed' | 'expired';
      storage_status: 'pending' | 'confirmed' | 'violation';
      site_readiness: 'not_started' | 'in_progress' | 'ready' | 'inspection_required' | 'approved';
      audit_action: 'create' | 'read' | 'update' | 'delete' | 'login' | 'logout' | 'export' | 'lock' | 'freeze' | 'approve' | 'reject' | 'ship' | 'receive';
      protocol_deviation_type: 'inclusion_criteria' | 'dosing' | 'schedule' | 'procedure' | 'documentation' | 'other';
      protocol_deviation_severity: 'minor' | 'major' | 'critical';
      monitoring_visit_type: 'pre_study' | 'periodic' | 'for_cause' | 'close_out';
    };
  };
};
